<a href="https://colab.research.google.com/github/harshaljanjani/statsForML/blob/main/Datacamp%20Courses/NumPy_20_01_2023_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy - Numeric Python Package - Datacamp**
### 1) Your First NumPy Array
### 2) Baseball player's height
### 3) Baseball player's BMI
### 4) Lightweight baseball players
### 5) NumPy Side Effects
### 6) Subsetting NumPy Arrays
### 7) 2D NumPy Arrays
### 8) Baseball data in 2D form
### 9) Subsetting 2D NumPy Arrays
### 10) 2D Arithmetic
### 11) NumPy: Basic Statistics
### 12) Average versus median
### 13) Explore the baseball data
### 14) Blend it all together


In [1]:
import numpy as np #NumPy -> Numeric Python

In [4]:
#Element wise calculations
#Efficient data structure for number crunching 
#NumPy arrays can contain only one data type, unlike regular python lists
#Enforces single data type in an array, hence able to drastically speed up the calculations 
height = [1.73,1.68,1.71,1.89,1.79]
weight = [65.4,59.2,63.6,88.4,68.7]
#weight/height**2
np_height = np.array(height)
np_weight = np.array(weight)
bmi = np_weight/np_height**2
print(bmi)
print(bmi>23) #NumPy array containing booleans -> [False,False,False,True,False]
print(bmi[bmi>23]) #Subsetting
print(type(bmi)) #numpy.ndarray(n-dimensional array)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
[False False False  True False]
[24.7473475]
<class 'numpy.ndarray'>


In [15]:
#2D-Arrays: Single Data Type
np_2d = np.array([height,weight])
print(np_2d.shape) #2 rows and 5 columns
print(np_2d[0][2])
print(np_2d[0,2])
#second and third family member's height and weight
print(np_2d[:,1:3])
#weight of all family members
print(np_2d[1,:])

(2, 5)
1.71
1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]


In [24]:
#Summarizing statistics about huge volumes of data:
#Data generation:
#Parameters for np.random.normal - distribution mean, distribution std, number of samples
height = np.round(np.random.normal(1.75,0.20,5000),2)
weight = np.round(np.random.normal(60.32,15,5000),2)
np_city = np.column_stack((height,weight)) #paste them together as columns

#Average/mean height from np_2d
print(np.mean(np_city[:,0]))
#Median height from np_city
print(np.median(np_city[:,0]))
#Check if height and weight of np_city are correlated - corrcoef()
print(np.corrcoef(np_city[:,0],np_city[:,0]))
#Std - standard deviation
print(np.std(np_city[:,0]))

1.753766
1.75
[[1. 1.]
 [1. 1.]]
0.2012985773521512


In [25]:
#Blend It All Together Exercise (Solution):
positions = ['GK', 'M', 'A', 'D']
heights = [191, 184, 185, 180]
# Import NumPy
import numpy as np
# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)
# Heights of the goalkeepers: gk_heights
isGk = (np_positions == 'GK')
gk_heights = np_heights[isGk]
# Heights of the other players: other_heights
isNotGk = (np_positions != 'GK')
other_heights = np_heights[isNotGk]
# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))
# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 191.0
Median height of other players: 184.0
